config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items do
    get "search", on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :main_category, class_name: "Item", foreign_key: "category1_id"
  has_many :sub_category, class_name: "Item", foreign_key: "category2_id"
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :main_category, class_name: "Category", foreign_key: "category1_id", optional: true
  belongs_to :sub_category, class_name: "Category", foreign_key: "category2_id", optional: true

  class << self
    def item_name_search(query)
      rel = order("item_no")
      if query.present?
        rel = rel.where("item_name LIKE ?", "%#{query}%")
      end
      rel
    end

    def item_no_search(query)
      rel = order("item_no")
      if query.present?
        rel = rel.where("item_no LIKE ?", "%#{query}%")
      end
      rel
    end

    def item_category1_search(query)
      rel = order("item_no")
      if query.present?
        rel = rel.joins(:main_category).where("category_name LIKE ?", "%#{query}%")
      end
      rel
    end

    def item_category2_search(query)
      rel = order("item_no")
      if query.present?
        rel = rel.joins(:sub_category).where("category_name LIKE ?", "%#{query}%")
      end
      rel
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def search
    @item = Item.new
    @categories = Category.select(:category_name)
    @items = Item.all.order(classification_no: "asc")
    @items = @items.item_no_search(params[:no]) if params[:no]
    @items = @items.item_name_search(params[:name]) if params[:name]
    @items = @items.item_category1_search(params[:main_category]) if params[:main_category]
    @items = @items.item_category2_search(params[:sub_category]) if params[:sub_category]

    render "new"
  end

  def new
    @item = Item.new
    @items = Item.all.order(item_no: "asc")
    @categories = Category.select(:category_name)
  end

  # def new
  #   @item = Item.new
  #   @items = Item.all.order(item_no: "asc")
  #   # render plain: @items.inspect
  #   @categories = Category.select(:category_name)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="form-content">
  <div class="form-parts form-first">
    <%= f.label @title, class:"form-label" %>
    <%= f.text_field :item_no, class: "form-input" %>
  </div>

  <div class="form-parts">
    <%= f.label @name, class: "form-label" %>
    <%= f.text_field :item_name, class: "form-input" %>
  </div>

  <div class="form-parts">
    <%= f.label @category1, class: "form-label" %>
    <%= f.collection_select :category1_id, @categories, :category_name, :category_name, class: "form-input" %>
  </div>

  <div class="form-parts">
    <%= f.label @category2, class: "form-label" %>
    <%= f.collection_select :category2_id, @categories, :category_name, :category_name, class: "form-input" %>
  </div>
</div>

app/views/items/_index.html.erb
<tr>
  <td><%= item.item_no %></td>
  <td><%= item.item_name %></td>
  <td><%= item.main_category.category_name %></td>
  <td><%= item.sub_category.category_name %></td>
  <td><%= link_to("編集", edit_item_path(item)) %></td>
  <td><%= link_to("削除", item_path(item), method: :delete, date: {confirm: "削除してもよろしいでしょうか？"}) %></td>
</tr>

app/views/items/_index_head.html.erb
<tr>
  <th>アイテムNO</th>
  <th>アイテム名</th>
  <th>分類１</th>
  <th>分類２</th>
  <th>編集</th>
  <th>削除</th>
</tr>

app/views/items/_search_form.html.erb
<%= form_tag :search_items, method: :get do %>
  <div class="form-content">
    <div class="form-parts form-first">
      <label class="form-label"><%= @title %></label>
      <%= text_field_tag :no, params[:no], placeholder: "", class: "form-input" %>
    </div>

    <div class="form-parts">
      <label class="form-label"><%= @name %></label>
      <%= text_field_tag :name, params[:name], placeholder: "", class: "form-input" %>
    </div>

    <div class="form-parts">
      <label class="form-label"><%= @category1 %></label>
      <%= text_field_tag :main_category, params[:main_category], placeholder: "", class: "form-input" %>
    </div>

    <div class="form-parts">
      <label class="form-label"><%= @category2 %></label>
      <%= text_field_tag :sub_category, params[:sub_category], placeholder: "", class: "form-input"%>
    </div>
  </div>
<div class="form-submit">
  <%= submit_tag "検索", class: "edit-bottn" %>
<% end %>
  <%= link_to "クリア", new_item_path, class: "clear" %>
</div>

app/views/items/new.html.erb
<% @title = "アイテムＮＯ：" %>
<% @name = "アイテム名：" %>
<% @category1 = "分類1：" %>
<% @category2 = "分類2：" %>

<div class="content-title"><h4>アイテム設定</h4></div>

<%= render "shared/errors", obj: @item %>

<div class="mein-content">
  <div class="left-content">
    <div class="form-title">
      <h4>新規登録</h4>
    </div>
    <%= form_for @item do |f| %>
      <%= render partial: "form", :locals => {f:f} %>
      <%= f.submit "新規登録", class: "edit-bottn" %>
    <% end %>
  </div>

  <div class="right-content">
    <div class="form-title">
      <h4>アイテム検索</h4>
    </div>
      <%= render partial: "search_form" %>
    <div class="index-title">
      <h4>検索結果一覧</h4>
    </div>
    <div class="index-content">
      <table>
        <%= render partial: "index_head" %>
        <% @items.each do | item | %>
          <%= render partial: "index", :locals => {item:item}  %>
        <% end %>
      </table>
    </div>
  </div>
</div>
<script>
  window.opener.location.reload();
</script>

<!-- </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.present? %>
  <div id="errors">
    <h3>エラーがあります。</h3>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>